# Generated by Django 2.1.4 on 2018-12-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_nome', models.CharField(max_length=30)),
                ('mod_descricao', models.CharField(max_length=150)),
                ('mod_url_name', models.CharField(max_length=200)),
            ],
        ),
    ]
