# Generated by Django 2.1.4 on 2018-12-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_menu', '0001_initial'),
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_nome', models.CharField(max_length=80)),
                ('men_url_name', models.CharField(max_length=150)),
                ('men_icon_class', models.CharField(max_length=150)),
                ('men_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.Modulo')),
                ('men_submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sub_menu.SubMenu')),
            ],
        ),
    ]
