# Generated by Django 2.1.4 on 2018-12-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_menu', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='men_submenu',
        ),
        migrations.AddField(
            model_name='menu',
            name='men_submenu',
            field=models.ManyToManyField(blank=True, null=True, to='sub_menu.SubMenu'),
        ),
    ]
