# Generated by Django 2.1.4 on 2018-12-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_nome', models.CharField(max_length=150)),
                ('fun_celular', models.CharField(max_length=15)),
                ('fun_gerente', models.BooleanField(default=False)),
                ('fun_setor_id', models.ManyToManyField(to='setores.Setor')),
                ('fun_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
